name: mjhutchison.com
favicon: null
layout_spectrum: 0.13321058498695493
typography_spectrum: 0.9238388498779386
title: mjhutchison.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6577345051337034
  lightness: 0.1278992381412536
  saturation: 0.20299445651471615
  rhythmicContrast: 0.902896060841158
purpose: []
